import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    let test = "<";
    let test2 = ">";
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div className={styles.main}>
              <h1 className={styles.title}>
                  弁当注文アプリモック 1
              </h1>
          </div>
          <div className={styles.maincontent}>
              <div className={styles.sub}>
                    <div className={styles.maincontent_date}>
                        <h1> {test}   2022/04   {test2} 2</h1>
                    </div>
                  <div className={styles.maincontent_inner}>
                    <Calendmox/>
                      <Calendmox/>
                  </div>
              </div>
          </div>
      </main>
    </>
  )
}

const Calendmox = () => {
    return (
        <div style={{margin: 30}}>
            <h1>Aランチ 3</h1>
            <div style={{ backgroundColor: "black" ,
                        color: "white",
                        borderRadius: 10 ,
                        padding: 14,
                        height: 300,
                        width: 500}}>
                image 4
            </div>
            <div style={{
                backgroundColor: "black" ,
                color: "white",
                height: 100,
                marginTop: 20,
                borderRadius: 10 ,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
            }}>
                <h1>カートに入れる 5</h1>
            </div>
            <div style={{
                backgroundColor: "black" ,
                color: "white",
                height: 100,
                marginTop: 20,
                borderRadius: 10 ,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
            }}>
                <h1>まとめて注文する 6</h1>
            </div>
        </div>
    );
}
